
all:
	   echo make all to start
	   echo make fetch to wget the textures... and so on for for the Pro New Gamer

fetch:
	   wget ftp://ftp.fu-berlin.de/pc/games/idgames/levels/doom2/Ports/megawads/aaliens.zip -O aaliens.zip
	    unzip aaliens.zip



play:
	  echo PRBOOM IS MORE THAN YOU !! LETS CRACK SOME HEADS !!
	  echo use prboom-plus if prboom is not there in your distro
	  prboom -iwad doom2.wad  -file aaliens.wad  map07-desert.wad 
	  prboom-plus -iwad doom2.wad  -file aaliens.wad  map07-desert.wad 



# no warranty: 
# http://doomgod.com/wads/iwads/








